/**
 * @file src/main/db/activity-log.repo.ts
 *
 * @created 07.03.2026
 * @modified 07.03.2026 *
 * @author Christian Blank <aidrelay@proton.me>
 * @copyright 2026
 *
 * @description Append-only repository for the activity log. Supports inserting
 * new entries and querying with optional filters. Records are never updated or
 * deleted — the full history is always preserved in SQLite.
 */

import type Database from 'better-sqlite3'
import type { ActivityLogEntry, LogFilters } from '@shared/channels'
import type { ClientId } from '@shared/types'

// ─── Row Shape ────────────────────────────────────────────────────────────────

/**
 * Raw row shape as returned by better-sqlite3 for the `activity_log` table.
 */
interface ActivityLogRow {
  id: number
  timestamp: string
  action: string
  details: string
  client_id: string | null
  server_id: string | null
}

// ─── Mapper ───────────────────────────────────────────────────────────────────

/**
 * Converts a raw database row into the shared `ActivityLogEntry` type.
 *
 * @param row - The raw SQLite row from the `activity_log` table.
 * @returns The hydrated `ActivityLogEntry` object.
 */
const rowToEntry = (row: ActivityLogRow): ActivityLogEntry => ({
  id: row.id,
  timestamp: row.timestamp,
  action: row.action,
  details: JSON.parse(row.details) as Record<string, unknown>,
  // With exactOptionalPropertyTypes, optional fields must be absent rather than
  // explicitly set to undefined — use a conditional spread to omit when null.
  ...(row.client_id != null && { clientId: row.client_id as ClientId }),
  ...(row.server_id != null && { serverId: row.server_id }),
})

// ─── Input Type ───────────────────────────────────────────────────────────────

/**
 * Payload for a new activity log entry. The `id` and `timestamp` are
 * auto-generated by the repository.
 */
export interface InsertLogInput {
  readonly action: string
  readonly details?: Readonly<Record<string, unknown>>
  readonly clientId?: ClientId
  readonly serverId?: string
}

// ─── Repository ───────────────────────────────────────────────────────────────

/**
 * Provides append-only access to the activity log.
 * Queries support filtering by action type, client, server, and date range.
 */
export class ActivityLogRepo {
  constructor(private readonly db: Database.Database) {}

  /**
   * Appends a new entry to the activity log.
   *
   * @param input - The event to record.
   * @returns The persisted `ActivityLogEntry` with its auto-assigned `id`.
   */
  insert(input: InsertLogInput): ActivityLogEntry {
    const timestamp = new Date().toISOString()

    const result = this.db
      .prepare(
        `INSERT INTO activity_log (timestamp, action, details, client_id, server_id)
         VALUES (?, ?, ?, ?, ?)`,
      )
      .run(
        timestamp,
        input.action,
        JSON.stringify(input.details ?? {}),
        input.clientId ?? null,
        input.serverId ?? null,
      )

    return {
      id: result.lastInsertRowid as number,
      timestamp,
      action: input.action,
      details: input.details ?? {},
      // Omit optional fields entirely rather than assigning undefined, to satisfy
      // exactOptionalPropertyTypes.
      ...(input.clientId !== undefined && { clientId: input.clientId }),
      ...(input.serverId !== undefined && { serverId: input.serverId }),
    }
  }

  /**
   * Queries the activity log with optional filters.
   * Results are returned in descending chronological order (newest first).
   *
   * @param filters - Optional constraints: action type, client, server, date range, result count.
   * @returns Matching `ActivityLogEntry` records.
   */
  query(filters: LogFilters = {}): ActivityLogEntry[] {
    const conditions: string[] = []
    const params: unknown[] = []

    if (filters.action) {
      conditions.push('action = ?')
      params.push(filters.action)
    }

    if (filters.clientId) {
      conditions.push('client_id = ?')
      params.push(filters.clientId)
    }

    if (filters.serverId) {
      conditions.push('server_id = ?')
      params.push(filters.serverId)
    }

    if (filters.since) {
      conditions.push('timestamp >= ?')
      params.push(filters.since)
    }

    const where = conditions.length > 0 ? `WHERE ${conditions.join(' AND ')}` : ''
    const limit = filters.limit ? `LIMIT ${filters.limit}` : ''

    const sql = `SELECT * FROM activity_log ${where} ORDER BY timestamp DESC ${limit}`
    const rows = this.db.prepare(sql).all(...params) as ActivityLogRow[]

    return rows.map(rowToEntry)
  }

  /**
   * Returns the newest sync event (`sync.performed` or `sync.failed`) for a
   * client, or `null` if no sync event has been logged yet.
   */
  findLatestSyncByClient(clientId: ClientId): ActivityLogEntry | null {
    const row = this.db
      .prepare(
        `SELECT * FROM activity_log
         WHERE client_id = ? AND action IN ('sync.performed', 'sync.failed')
         ORDER BY timestamp DESC
         LIMIT 1`,
      )
      .get(clientId) as ActivityLogRow | undefined

    return row ? rowToEntry(row) : null
  }
}
